[sdk]
#WebSocket operating mode, client: client mode, server: server mode
role=server
#WebSocket IP address: effective under client mode
ip=127.0.0.1
#WebSocket communication port
port=9002
#WebSocket heartbeat judgment switch, not effective in server mode, 1: enable heartbeat judgment, 0: disable heartbeat judgment; 
#The default is "disable heartbeat judgment" if not configured.
heartBeatOnOff=0
#WebSocket heartbeat judgment interval, not effective in server mode, range: 10-60 seconds; Default is "60 seconds" if not configured.
heartBeat=20
#WebSocket heartbeat judgment mode，not effective in server mode， 1：WSCmdApp actively sending heartbeat commands   0：WSCmdApp passive reception of heartbeat commands
heartBeatMode=0
#WSCmdApp exits, 1: exit command is valid, 0: exit command is invalid
WSExit=1
#WSCmdApp language, 0: Simplified Chinese, 1: English.
language=0
#Use base station ID or base station SN in JSON commands, 0: base station ID, 1: base station SN.
jsonBase=0
#Log upload switch 1: Enable log upload 0: Disable log upload
logUpload=0